name: bcvk-ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    container:
      image: docker://dhi.io/debian-base@sha256:9415967aa0ed8adea8b5c048994259d1982026dca143d0303c7bbe0e11ed67d3
      options: --help
      credentials:
        username: 0mniteck42
        password: ${{secrets.DOCKER}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run Install
        run: |
          apt-get -qq update && apt-get -qq install --no-install-recommends build-essential curl git openssl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Run Cargo Tests
        run: |
          cargo test -p bcvk --lib native_to_disk::
          cargo test -p bcvk-qemu --lib usb_passthrough::
          cargo check --workspace
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Cargo Workspace Warnings
        run: cargo clippy --workspace -- -D warnings
      - name: Git Status
        run: git status 
